/*
 * Copyright © 2026, Bitshift ED <https://bitshifted.co>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package co.bitshifted.mdviewfx.model;

/** Types of messages supported by the chat UI. */
public enum MessageType {
  /** Message sent by the local user. */
  USER,

  /** Message sent by a chat participant other than current user. */
  PARTICIPANT,

  /** Message generated by an AI assistant. */
  AI
}
